Repository Webwiznitr/Project-basil, pull requests merged in 2020-10, with the labels that each got.

#14 Header files
  header.css
  header.html
  header.js
  images/header.png
Labels: hacktoberfest, hacktoberfest2020

#18 Image Changed
  images/ad.png
  images/ai.png
  images/cpro.png
  images/cysec.jpg
  images/ml
  images/wdes.jpg
  index.html
Labels: hacktoberfest, hacktoberfest2020

#19 Footer files
  footer.html
  header.js
  header_footer.css
  images/footer.jpg
  main.js
Labels: hacktoberfest, hacktoberfest2020

#23 Enhanced the UI for the home page and the web-development-road map.
  Course/img/Thumbs.db
  Course/img/computer.png
  Course/img/machine.jpg
  Course/img/webdev.png
  Course/index.html
  Course/style.css
  images/Thumbs.db
  images/abstract.jpg
  images/bg2.jpg
  images/digital.jpg
  index.html
  style.css
Labels: hacktoberfest, hacktoberfest2020

#21 Created a course folder for ML and added machine learning resources
  Course/Machine Learning/Learn ML from Online Courses.docx
  Course/Machine Learning/Learn ML from Youtube.docx
  Course/Machine Learning/Learn ML from blogs and books.docx
Labels: documentation, hacktoberfest, hacktoberfest2020

#26 CyberSecurityMaterial
  Course/Cyber Security/Learn Cyber Security from Online Courses.docx
  Course/Cyber Security/Learn Cyber Security from Youtube.docx
  Course/Cyber Security/Learn Cyber Security from blogs and books.docx
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2020

#31 Database Management Course
  images/databasemgmnt.png
  index.html
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2020

#34 Created a text file containing links to online AI tutorials
  Course/Artificial Intelligence/Learn AI from online tutorials.docx
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2020

#29 CSS - newsletter button and course title hovers
  assets/css/style.css
Labels: hacktoberfest-accepted

#39 android app development learning material
  Course/Android app dev/ANDROID DEV COURSE.docx
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2020

#44 Add Web-Development Resources
  Course/Web-Devlopment/Learn Web-Development From Youtube.docx
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2020

#43 Change up styles of Homepage
  assets/css/style.css
  index.html
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2020
